btelecom/btelecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("btelecomapp.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

btelecom/btelecomapp/urls.py
from django.urls import path
from.views import *


app_name = "btelecomapp"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("search_results/", SearchResultsView.as_view(), name="search_results"),
    path("form/", FormView.as_view(), name="form"),
    path("dataform/", SearchView.as_view(), name="SearchView"),
    ]

btelecom/btelecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL
from django.db.models.fields import DateTimeField

# Create your models here.

ELEMENTOS=(
    ("Crossconennect","Crossconennect"),
    ("Mimo","Mimo"),
    ("Diplexer","Diplexer"),
    ("Triplexer","Triplexer"),
    ("Quadriplexer","Quadriplexer"),
    ("Mixmode","Mixmode"),
    ("Powersplit","Powersplit"),
    ("Radio Compartilhada","Radio Compartilhada"),
    ("Mais Elementos","Mais Elementos"),
)

class Solucoes(models.Model):
    titulo = models.CharField(max_length=200)
    numero = models.PositiveIntegerField(unique=True)
    elementos = models.CharField(max_length=50,choices=ELEMENTOS)
    qtdportas = models.PositiveIntegerField()
    porta1 = models.CharField(max_length=200)
    porta2 = models.CharField(max_length=200)
    porta3 = models.CharField(max_length=200)
    porta4 = models.CharField(max_length=200)
    porta5 = models.CharField(max_length=200)
    porta6 = models.CharField(max_length=200)
    image = models.ImageField(upload_to="produtos")
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id) + ' - ' + str(self.titulo)

btelecom/btelecomapp/views.py
from django.db.models.query_utils import select_related_descend
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from.models import *
from django.http import HttpResponse, request

# Create your views here.

class HomeView(ListView):
    template_name = "home.html"
    model = Solucoes
    context_object_name = 'home'
    paginate_by = 3
    queryset = Solucoes.objects.all().order_by("-criado_em")

class SearchResultsView(ListView):
    template_name = "search_results.html"
    model = Solucoes
    context_object_name = 'search_results'
    paginate_by = 10
    queryset = Solucoes.objects.all().order_by("-criado_em")
    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Solucoes.objects.filter(
            Q(porta1__icontains=query)
        ).order_by("-criado_em")
        return object_list

class FormView(ListView):
    template_name = "form.html"
    model = Solucoes
    context_object_name = 'form'
    queryset = Solucoes.objects.all().order_by("-criado_em")
    
class SearchView(ListView):
    template_name = "dataform.html"
    model = Solucoes
    context_object_name = 'SearchView'
    paginate_by = 10
    queryset = Solucoes.objects.all().order_by("-criado_em")
    def SearchView(request):
        porta1=(request.GET.get('id_porta1'))
        porta2=(request.GET.get('id_porta2'))
        porta3=(request.GET.get('id_porta3'))
        porta4=(request.GET.get('id_porta4'))
        porta5=(request.GET.get('id_porta5'))
        porta6=(request.GET.get('id_porta6'))
        object_list = Solucoes.objects.filter(
            Q(porta1=porta1) | Q(porta2=porta2) | Q(porta3=porta3) | Q(porta4=porta4) | Q(porta5=porta5) | Q(porta5=porta6)
        ).order_by("-criado_em")
        print(porta1)
        return object_list

btelecom/templates/base.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'btelecomapp:home' %}">Bezerra Telecom</a>
    <form action="{% url 'btelecomapp:search_results' %}" method="get" class="d-flex">
      <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

{% block content %}

{% endblock content %}

</body>

btelecom/templates/dataform.html
{% extends 'base.html' %}

{% block title %}form{% endblock title %}

{% block content %}

<div class="container">
    <h1>Buscando Soluções</h1>
    <div>
        <form id="SearchView" action="{% url 'btelecomapp:SearchView' %}" method="GET">
          <label for="id_porta1">Porta 1:</label>
                <select name="id_porta1" id="id_porta1">
                <option selected="selected">----</option>
                {% for cat in SearchView %}
                    <option value="{{cat.porta1}}">{{cat.porta1}}</option>
                {% endfor %}
                </select>

            <label for="id_porta2">Porta 2:</label>
                <select name="id_porta2" id="id_porta2">
                <option selected="selected">----</option>
                {% for cat in SearchView %}
                    <option value="{{cat.porta2}}">{{cat.porta2}}</option>
                {% endfor %}
                </select>

            <label for="id_porta3">Porta 3:</label>
                <select name="id_porta3" id="id_porta3">
                <option selected="selected">----</option>
                {% for cat in SearchView %}
                    <option value="{{cat.porta3}}">{{cat.porta3}}</option>
                {% endfor %}
                </select>

            <label for="id_porta4">Porta 4:</label>
                <select name="id_porta4" id="id_porta4">
                <option selected="selected">----</option>
                {% for cat in SearchView %}
                    <option value="{{cat.porta4}}">{{cat.porta4}}</option>
                {% endfor %}
                </select>

            <label for="id_porta5">Porta 5:</label>
                <select name="id_porta5" id="id_porta5">
                <option selected="selected">----</option>
                {% for cat in SearchView %}
                    <option value="{{cat.porta5}}">{{cat.porta5}}</option>
                {% endfor %}
                </select>

            <label for="id_porta6">Porta 6:</label>
                <select name="id_porta6" id="id_porta6">
                <option selected="selected">----</option>
                {% for cat in SearchView %}
                    <option value="{{cat.porta6}}">{{cat.porta6}}</option>
                {% endfor %}
                </select>
            <input class="btn btn-outline-success" type="submit">
        </form>
    </div>
</div>

<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Titulo</th>
                <th scope="col">Numero</th>
                <th scope="col">Porta 1</th>
                <th scope="col">Porta 2</th>
                <th scope="col">Porta 3</th>
                <th scope="col">Porta 4</th>
                <th scope="col">Porta 5</th>
                <th scope="col">Porta 6</th>
                <th scope="col">Elementos</th>
                <th scope="col">Qtd. de Porta</th>
                <th scope="col">Imagem</th>
            </tr>
        </thead>
        <tbody>
        {% for cat in SearchView %}
            <tr>
                <td><h6>{{cat.criado_em}}</h6></td>
                <td>{{cat.titulo}}</td>
                <td>{{cat.numero}}</td>
                <td>{{cat.porta1}}</td>
                <td>{{cat.porta2}}</td>
                <td>{{cat.porta3}}</td>
                <td>{{cat.porta4}}</td>
                <td>{{cat.porta5}}</td>
                <td>{{cat.porta6}}</td>
                <td>{{cat.elementos}}</td>
                <td>{{cat.qtdportas}}</td>
                <td>
                    <a href="{{ cat.image.url }}" target="_blank">
                        <img src="{{ cat.image.url }}" alt="" class="img-fluid" style="height: 50px; object-fit: cover;">
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<nav aria-label="Page navigation example">
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-link" ><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-link" ><span>{{ i }} <span class="sr-only"></span></span></li>
        {% else %}
            <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-link"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</nav>

</div>

{% endblock %}

btelecom/templates/form.html
{% extends 'base.html' %}

{% block title %}form{% endblock title %}

{% block content %}

<div class="container">
    <h1>Buscando Soluções</h1>
    <div>
        <form id="SearchView" action="{% url 'btelecomapp:SearchView' %}" method="GET">
          <label for="id_porta1">Porta 1:</label>
                <select name="id_porta1" id="id_porta1">
                <option selected="selected">----</option>
                {% for cat in form %}
                    <option value="{{cat.porta1}}">{{cat.porta1}}</option>
                {% endfor %}
                </select>

            <label for="id_porta2">Porta 2:</label>
                <select name="id_porta2" id="id_porta2">
                <option selected="selected">----</option>
                {% for cat in form %}
                    <option value="{{cat.porta2}}">{{cat.porta2}}</option>
                {% endfor %}
                </select>

            <label for="id_porta3">Porta 3:</label>
                <select name="id_porta3" id="id_porta3">
                <option selected="selected">----</option>
                {% for cat in form %}
                    <option value="{{cat.porta3}}">{{cat.porta3}}</option>
                {% endfor %}
                </select>

            <label for="id_porta4">Porta 4:</label>
                <select name="id_porta4" id="id_porta4">
                <option selected="selected">----</option>
                {% for cat in form %}
                    <option value="{{cat.porta4}}">{{cat.porta4}}</option>
                {% endfor %}
                </select>

            <label for="id_porta5">Porta 5:</label>
                <select name="id_porta5" id="id_porta5">
                <option selected="selected">----</option>
                {% for cat in form %}
                    <option value="{{cat.porta5}}">{{cat.porta5}}</option>
                {% endfor %}
                </select>

            <label for="id_porta6">Porta 6:</label>
                <select name="id_porta6" id="id_porta6">
                <option selected="selected">----</option>
                {% for cat in form %}
                    <option value="{{cat.porta6}}">{{cat.porta6}}</option>
                {% endfor %}
                </select>
            <input class="btn btn-outline-success" type="submit" name="busca" id="busca" value="busca">
        </form>
    </div>
</div>

<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Titulo</th>
                <th scope="col">Numero</th>
                <th scope="col">Porta 1</th>
                <th scope="col">Porta 2</th>
                <th scope="col">Porta 3</th>
                <th scope="col">Porta 4</th>
                <th scope="col">Porta 5</th>
                <th scope="col">Porta 6</th>
                <th scope="col">Elementos</th>
                <th scope="col">Qtd. de Porta</th>
                <th scope="col">Imagem</th>
            </tr>
        </thead>
        <tbody>
        {% for cat in form %}
            <tr>
                <td><h6>{{cat.criado_em}}</h6></td>
                <td>{{cat.titulo}}</td>
                <td>{{cat.numero}}</td>
                <td>{{cat.porta1}}</td>
                <td>{{cat.porta2}}</td>
                <td>{{cat.porta3}}</td>
                <td>{{cat.porta4}}</td>
                <td>{{cat.porta5}}</td>
                <td>{{cat.porta6}}</td>
                <td>{{cat.elementos}}</td>
                <td>{{cat.qtdportas}}</td>
                <td>
                    <a href="{{ cat.image.url }}" target="_blank">
                        <img src="{{ cat.image.url }}" alt="" class="img-fluid" style="height: 50px; object-fit: cover;">
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<nav aria-label="Page navigation example">
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-link" ><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-link" ><span>{{ i }} <span class="sr-only"></span></span></li>
        {% else %}
            <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-link"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</nav>

</div>

{% endblock %}

btelecom/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Titulo</th>
                <th scope="col">Numero</th>
                <th scope="col">Descrição</th>
                <th scope="col">Elementos</th>
                <th scope="col">Porta</th>
                <th scope="col">Imagem</th>
            </tr>
        </thead>
        <tbody>
        {% for cat in home %}
            <tr>
                <td>{{cat.criado_em}}</td>
                <td>{{cat.titulo}}</td>
                <td>{{cat.numero}}</td>
                <td>{{cat.descricao}}</td>
                <td>{{cat.elementos}}</td>
                <td>{{cat.portas}}</td>
                <td>
                    <a href="{{ cat.image.url }}" target="_blank">
                        <img src="{{ cat.image.url }}" alt="" class="img-fluid" style="height: 50px; object-fit: cover;">
                    </a>
                </td>
            </tr>
        {% endfor %} 
        </tbody>
    </table>

<nav aria-label="Page navigation example">
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-link" ><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-link" ><span>{{ i }} <span class="sr-only"></span></span></li>
        {% else %}
            <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-link"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</nav>

</div>


{% endblock %}

btelecom/templates/search_results.html
{% extends 'base.html' %}

{% block title %}SearchResultsView{% endblock title %}

{% block content %}

<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Titulo</th>
                <th scope="col">Numero</th>
                <th scope="col">Porta 1</th>
                <th scope="col">Porta 2</th>
                <th scope="col">Porta 3</th>
                <th scope="col">Porta 4</th>
                <th scope="col">Porta 5</th>
                <th scope="col">Porta 6</th>
                <th scope="col">Elementos</th>
                <th scope="col">Qtd. de Porta</th>
                <th scope="col">Imagem</th>
            </tr>
        </thead>
        <tbody>
        {% for cat in search_results %}
            <tr>
                <td><h6>{{cat.criado_em}}</h6></td>
                <td>{{cat.titulo}}</td>
                <td>{{cat.numero}}</td>
                <td>{{cat.porta1}}</td>
                <td>{{cat.porta2}}</td>
                <td>{{cat.porta3}}</td>
                <td>{{cat.porta4}}</td>
                <td>{{cat.porta5}}</td>
                <td>{{cat.porta6}}</td>
                <td>{{cat.elementos}}</td>
                <td>{{cat.qtd_portas}}</td>
                <td>
                    <a href="{{ cat.image.url }}" target="_blank">
                        <img src="{{ cat.image.url }}" alt="" class="img-fluid" style="height: 50px; object-fit: cover;">
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<nav aria-label="Page navigation example">
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-link" ><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-link" ><span>{{ i }} <span class="sr-only"></span></span></li>
        {% else %}
            <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-link"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</nav>

</div>


{% endblock %}